baseURL = "https://blog.astrokube.com/"
languageCode = "en-us"
title = "AstroKube - developers blog ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»"
relativeURLs           = true
canonifyUrls           = true
theme = "astro"
summaryLength = 20
copyright = "Astrokube. All rights reserved."
# sectionPagesMenu = "main"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

defaultContentLanguage = "en"

# --------------------
# [languages.en]
[languages.en]
title = "AstroKube - developers blog ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»"
weight = 1

[[languages.en.menu.main]]
url    = "/"
name   = "Blog"
weight = 1

[[languages.en.menu.main]]
url    = "/tags/"
name   = "Tags"
weight = 2

[[languages.en.menu.main]]
url    = "/contact/"
name   = "Contact"
weight = 3

# --------------------
# [languages.es]
[languages.es]
title = "AstroKube - blog de desarrolladores ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»"
weight = 2

[[languages.es.menu.main]]
url    = "/es/"
name   = "Blog"
weight = 1

[[languages.es.menu.main]]
url    = "/es/tags/"
name   = "Etiquetas"
weight = 2

[[languages.es.menu.main]]
url    = "/es/contact/"
name   = "Contacto"
weight = 3

# --------------------
# [params]
[params]
  logoSRC = "/images/logo.svg"
  logoURL = "https://astrokube.com/"
  logoTitle = "AstroKube homepage"
  body_classes = "bg-light"
  paginate = 2
  mainSections = ["post"]

[[params.contactsfooter]]
name = "email"
url = "mailto:info@astrokube.com"
icon = "bi-envelope-fill"

[[params.contactsfooter]]
name = "twitter"
url = "https://twitter.com/astrokube"
icon = "bi-twitter"

[[params.contactsfooter]]
name = "github"
url = "https://github.com/astrokube"
icon = "bi-github"
